version: '3'

services:
    api_db:
        image: postgres:11
        volumes:
            - ./.ignore/postgres/postgres:/var/lib/postgresql/data
        environment: 
            - POSTGRES_NAME=postgres
            - NEW_POSTGRES_NAME=postgres
            - POSTGRES_PASSWORD=postgres 
            - POSTGRES_USER=postgres 
            - POSTGRES_DB=postgres
        ports:
            - "5435:80"
    api:
        build: .
        command: ["sh", "scripts/start.sh"]
        volumes:
            - .:/code 
        ports:
            - "8000:8000"
        depends_on:
            - api_db