# Generated by Django 3.0.1 on 2020-01-23 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcampsQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Título do Questionario')),
            ],
        ),
        migrations.CreateModel(
            name='DifficultySet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('easy', models.IntegerField(default=50, verbose_name='F - Fácil')),
                ('medium', models.IntegerField(default=100, verbose_name='M - Médio')),
                ('hard', models.IntegerField(default=150, verbose_name='H - Difícil')),
                ('expert', models.IntegerField(default=200, verbose_name='E - Expert')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150, unique=True, verbose_name='Nome da equipe')),
                ('hits', models.IntegerField(default=0, verbose_name='Acertos')),
                ('points', models.IntegerField(default=0, verbose_name='Pontuação')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(default='', max_length=255, verbose_name='Enunciado da questão')),
                ('difficulty', models.CharField(default='M', max_length=1, verbose_name='Dificuldade')),
                ('acamp_questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='acamps_questions.AcampsQuestions')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='acamps_questions.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=150, verbose_name='Texto da alternativa')),
                ('validate', models.BooleanField(default=False, verbose_name='Validador da alternativa')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternartives', to='acamps_questions.Question')),
            ],
        ),
        migrations.AddField(
            model_name='acampsquestions',
            name='difficulty_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='difficulty_set', to='acamps_questions.DifficultySet'),
        ),
    ]
