# Generated by Django 3.0.1 on 2020-01-23 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acamps_questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acampsquestions',
            name='difficulty_set',
        ),
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
        migrations.DeleteModel(
            name='DifficultySet',
        ),
    ]
