# Generated by Django 3.0.1 on 2020-02-19 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acamps_questions', '0002_auto_20200123_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='acamps_questions.Team'),
        ),
    ]
