# Generated by Django 3.0.3 on 2020-02-20 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acamps_questions', '0003_auto_20200219_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acamps_questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='acamps_questions.AcampsQuestions')),
            ],
        ),
    ]
