# Generated by Django 3.0.3 on 2020-02-20 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acamps_questions', '0005_auto_20200220_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='session',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='session', to='acamps_questions.Session'),
            preserve_default=False,
        ),
    ]
