# Generated by Django 3.0.3 on 2020-02-20 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acamps_questions', '0006_auto_20200220_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session', to='acamps_questions.Session'),
        ),
    ]
