# Generated by Django 3.0.1 on 2019-12-27 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('bible', models.BooleanField(default=False)),
                ('lesson', models.BooleanField(default=False)),
                ('presence', models.BooleanField(default=False)),
                ('reading', models.BooleanField(default=False)),
                ('visitor', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'class_register',
            },
        ),
    ]
