# Generated by Django 3.0.6 on 2020-05-05 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EBD', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebdclass',
            name='teacher',
        ),
        migrations.AddField(
            model_name='ebduser',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ebd_teacher', to='EBD.EBDClass'),
        ),
    ]
