# Generated by Django 3.0.6 on 2020-05-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EBD', '0002_auto_20200505_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebduser',
            name='teacher',
            field=models.BooleanField(default=False),
        ),
    ]
