# Generated by Django 3.0.1 on 2019-12-31 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EBD', '0003_ebdclass_ebduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classregister',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_register', to='EBD.EBDUser'),
        ),
    ]
