# Generated by Django 3.0.1 on 2019-12-31 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EBD', '0004_auto_20191231_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebduser',
            name='ebd_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebd_class', to='EBD.EBDClass'),
        ),
    ]
