# Generated by Django 3.0.1 on 2019-12-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EBD', '0005_auto_20191231_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebdclass',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
