# Generated by Django 3.0.1 on 2020-01-15 01:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EBD', '0006_auto_20191231_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebdclass',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='EBD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('classes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='EBD.EBDClass')),
            ],
            options={
                'db_table': 'ebd',
            },
        ),
    ]
