# Generated by Django 3.0.1 on 2020-01-15 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EBD', '0007_auto_20200114_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebd',
            name='classes',
        ),
        migrations.AddField(
            model_name='classregister',
            name='cult',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ebd',
            name='lesson_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_class', to='EBD.EBDClass'),
        ),
        migrations.AddField(
            model_name='ebd',
            name='lesson_theme',
            field=models.CharField(blank=True, default='', help_text='Tema da EBD', max_length=255),
        ),
    ]
